project_id = "yrebxnpilkfeaofykvhq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[functions.weather]
verify_jwt = true

[functions.kisan-chat]
verify_jwt = true

[functions.crop-doctor]
verify_jwt = true

[functions.mandi-prices]
verify_jwt = true

[functions.nearby-services]
verify_jwt = true

[functions.tractor-hire]
verify_jwt = true

[functions.agri-market]
verify_jwt = true

[functions.scheme-finder]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.agri-news]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = true
