import type { AppNotification } from './notificationTypes';

const day = 24 * 60 * 60 * 1000;
const hoursAgo = (h: number): string => new Date(Date.now() - h * 3600 * 1000).toISOString();
const daysAgo = (d: number): string => new Date(Date.now() - d * day).toISOString();

export const seedNotifications = (): AppNotification[] => [
  {
    id: 'seed-1',
    category: 'weather',
    severity: 'critical',
    titleKey: 'notif.rain.title',
    bodyKey: 'notif.rain.body',
    params: { place: 'Shivpuri', rain: 82 },
    createdAt: hoursAgo(3),
    read: false,
    dismissed: false,
    delivery: 'both',
    pushSent: false,
    dedupeKey: 'rain-seed',
    actions: [{ id: 'view', labelKey: 'notif.action.view', tab: 'home', variant: 'primary' }],
  },
  {
    id: 'seed-2',
    category: 'mandi',
    severity: 'alert',
    titleKey: 'notif.mandiPrice.title',
    bodyKey: 'notif.mandiPrice.body',
    params: { crop: 'Wheat', price: '2,420', target: '2,400' },
    createdAt: hoursAgo(8),
    read: false,
    dismissed: false,
    delivery: 'both',
    pushSent: false,
    dedupeKey: 'mandi-seed',
    actions: [
      { id: 'view', labelKey: 'notif.action.view', tab: 'mandi', variant: 'primary' },
      { id: 'alert', labelKey: 'notif.action.manage', tab: 'price-alerts', variant: 'ghost' },
    ],
  },
  {
    id: 'seed-3',
    category: 'scheme',
    severity: 'alert',
    titleKey: 'notif.schemeDeadline.title',
    bodyKey: 'notif.schemeDeadline.body',
    params: { scheme: 'PM-KISAN', days: 4 },
    createdAt: daysAgo(1),
    read: false,
    dismissed: false,
    delivery: 'in-app',
    pushSent: false,
    dedupeKey: 'scheme-seed',
    actions: [{ id: 'view', labelKey: 'notif.action.view', tab: 'schemes', variant: 'primary' }],
  },
  {
    id: 'seed-4',
    category: 'payment',
    severity: 'info',
    titleKey: 'notif.paymentSuccess.title',
    bodyKey: 'notif.paymentSuccess.body',
    params: { amount: '₹1,250' },
    createdAt: daysAgo(2),
    read: true,
    dismissed: false,
    delivery: 'both',
    pushSent: true,
    actions: [{ id: 'view', labelKey: 'notif.action.view', tab: 'wallet', variant: 'primary' }],
  },
  {
    id: 'seed-5',
    category: 'booking',
    severity: 'info',
    titleKey: 'notif.bookingConfirmed.title',
    bodyKey: 'notif.bookingConfirmed.body',
    params: { tractor: 'Mahindra 575 DI', date: 'Tomorrow, 7 AM' },
    createdAt: daysAgo(2),
    read: true,
    dismissed: false,
    delivery: 'both',
    pushSent: true,
    actions: [{ id: 'view', labelKey: 'notif.action.view', tab: 'tractors', variant: 'primary' }],
  },
  {
    id: 'seed-6',
    category: 'ai',
    severity: 'info',
    titleKey: 'notif.aiRecommendation.title',
    bodyKey: 'notif.aiRecommendation.body',
    params: { crop: 'soybean' },
    createdAt: daysAgo(3),
    read: true,
    dismissed: false,
    delivery: 'in-app',
    pushSent: false,
    actions: [{ id: 'view', labelKey: 'notif.action.ask', tab: 'ai-chat', variant: 'primary' }],
  },
  {
    id: 'seed-7',
    category: 'task',
    severity: 'alert',
    titleKey: 'notif.taskDue.title',
    bodyKey: 'notif.taskDue.body',
    params: { task: 'Second split of urea', days: 1 },
    createdAt: daysAgo(4),
    read: true,
    dismissed: false,
    delivery: 'in-app',
    pushSent: false,
    actions: [{ id: 'view', labelKey: 'notif.action.view', tab: 'crop-calendar', variant: 'primary' }],
  },
  {
    id: 'seed-8',
    category: 'reminder',
    severity: 'info',
    titleKey: 'notif.irrigation.title',
    bodyKey: 'notif.irrigation.body',
    params: { crop: 'soybean', day: 'Saturday' },
    createdAt: daysAgo(5),
    read: true,
    dismissed: false,
    delivery: 'in-app',
    pushSent: false,
    actions: [{ id: 'view', labelKey: 'notif.action.view', tab: 'crop-calendar', variant: 'primary' }],
  },
  {
    id: 'seed-9',
    category: 'order',
    severity: 'info',
    titleKey: 'notif.orderShipped.title',
    bodyKey: 'notif.orderShipped.body',
    params: { order: '#A-1142' },
    createdAt: daysAgo(6),
    read: true,
    dismissed: false,
    delivery: 'both',
    pushSent: true,
    actions: [{ id: 'view', labelKey: 'notif.action.view', tab: 'store', variant: 'primary' }],
  },
];
