import { Link } from 'react-router-dom';
import { SeoHead } from '@/components/seo/SeoHead';
import { canonical, ogImage } from '@/lib/seo-config';
import MarketingBreadcrumb from '@/shared/layouts/MarketingBreadcrumb';

const SECTIONS = [
  {
    title: '1. Information We Collect',
    content:
      'We collect information you provide directly (name, phone, email, farm details, location), data generated by your use (crop scans, mandi searches, weather views, bookings), and device information (language preference, app version). We never sell your personal data.',
  },
  {
    title: '2. How We Use Your Data',
    content:
      'Your data powers the features you use: live mandi prices, crop diagnosis, weather forecasts, scheme eligibility, and community connections. We use aggregated, anonymized data to improve our AI models and services. Location data is used only to show local mandis, weather, and nearby services.',
  },
  {
    title: '3. Data Storage & Security',
    content:
      'Your data is encrypted in transit (TLS) and at rest. We follow Indian data protection principles and industry best practices. Offline data is stored securely on your device and synced only when you choose.',
  },
  {
    title: '4. Sharing of Information',
    content:
      'We share your data only with: (a) service providers who help us operate (hosting, SMS/WhatsApp, analytics) under strict confidentiality, (b) tractor/machinery owners and buyers when you transact on the marketplace, and (c) authorities when legally required.',
  },
  {
    title: '5. Your Rights',
    content:
      'You can access, correct, export, or delete your personal data at any time from Settings → Privacy. Account deletion removes your data within 30 days. You may also withdraw consent for non-essential processing.',
  },
  {
    title: '6. Location & Permissions',
    content:
      'AgriConnect asks for location only to show nearby mandis, weather, and tractor rental options. You can use the app without precise location. Camera access is used only for crop scans and profile photos.',
  },
  {
    title: '7. Children\'s Privacy',
    content:
      'AgriConnect is not directed at children under 13. We do not knowingly collect personal data from children.',
  },
  {
    title: '8. Changes to This Policy',
    content:
      'We may update this policy from time to time. Material changes will be notified in-app and on this page. Continued use after changes constitutes acceptance.',
  },
  {
    title: '9. Contact Us',
    content:
      'For privacy questions, email privacy@agriconnect.in or write to our head office. We respond within 30 days.',
  },
];

const PrivacyPolicy: React.FC = () => {
  const jsonLd = [
    {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: 'Privacy Policy — AgriConnect',
      url: canonical('/privacy-policy'),
      description: 'How AgriConnect collects, uses, and protects your personal data.',
      isPartOf: { '@id': `${canonical('/')}#website` },
    },
  ];

  return (
    <>
      <SeoHead
        title="Privacy Policy — AgriConnect"
        description="Learn how AgriConnect collects, uses, and protects farmer data. Your privacy matters — we never sell your data. Read our full privacy policy."
        canonical="/privacy-policy"
        keywords={['AgriConnect privacy policy', 'farmer data privacy', 'agriculture app privacy', 'data protection India']}
        ogType="website"
        ogImage={ogImage()}
        robots="index, follow"
        jsonLd={jsonLd}
      />

      <main className="min-h-screen bg-background pb-20">
        <header className="bg-gradient-to-br from-emerald-800 via-teal-800 to-emerald-900 text-white">
          <div className="mx-auto max-w-4xl px-4 py-12 md:py-16">
            <MarketingBreadcrumb
              tone="light"
              items={[{ label: 'Home', path: '/' }, { label: 'Privacy Policy' }]}
            />
            <h1 className="text-3xl md:text-4xl font-black tracking-tight">Privacy Policy</h1>
            <p className="text-emerald-100/80 mt-2">Last updated: January 2026</p>
          </div>
        </header>

        <div className="mx-auto max-w-4xl px-4 py-10">
          <p className="text-muted-foreground leading-relaxed mb-8">
            This Privacy Policy explains how AgriConnect Technologies Pvt. Ltd. ("AgriConnect",
            "we", "us") collects, uses, and protects your information when you use our website,
            mobile app, and services. By using AgriConnect, you agree to this policy.
          </p>

          <div className="space-y-6">
            {SECTIONS.map((s) => (
              <section key={s.title} className="rounded-2xl border border-border bg-card p-6 shadow-card">
                <h2 className="font-bold text-foreground text-lg">{s.title}</h2>
                <p className="text-muted-foreground text-sm leading-relaxed mt-2">{s.content}</p>
              </section>
            ))}
          </div>

          <div className="mt-10 rounded-2xl gradient-hero text-primary-foreground p-6 text-center">
            <h2 className="font-bold text-xl">Questions about privacy?</h2>
            <p className="text-sm text-primary-foreground/80 mt-2">We're happy to clarify.</p>
            <Link
              to="/contact"
              className="inline-block mt-4 rounded-lg bg-white text-emerald-900 px-5 py-2.5 font-semibold text-sm hover:bg-emerald-50 transition"
            >
              Contact Us
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default PrivacyPolicy;

