// One-time generator: extracts a compact, honest bootstrap manifest from the
// curated static scheme catalog and emits
// supabase/functions/agri-sync-worker/curated-schemes.ts
// Run: node -r ts-node/register scripts/agri-manifest.cts
import * as path from "path";
import * as fs from "fs";
import { fileURLToPath } from "url";
import { VERIFIED_GOVERNMENT_SCHEMES } from "../src/lib/government-schemes-data.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

type CatStatus = "open" | "urgent" | "soon" | "rolling" | "closed";

const STATUS_MAP: Record<CatStatus, string> = {
  open: "active",
  rolling: "rolling",
  urgent: "active",
  soon: "upcoming",
  closed: "closed",
};

const manifest = VERIFIED_GOVERNMENT_SCHEMES.map((s) => ({
  id: s.id,
  code: s.code,
  name: s.title,
  nameHi: s.titleHi,
  category: s.category,
  level: s.level,
  applicableStates: s.applicableStates,
  ministry: s.ministry,
  benefits: s.benefit,
  benefitAmount: s.benefitAmount,
  benefitAmountNum: s.benefitAmountNum,
  description: s.summary,
  descriptionHi: (s as { summaryHi?: string }).summaryHi || null,
  applicationUrl: s.applyUrl,
  officialUrl: s.applyUrl,
  helpline: s.contactHelpline,
  status: STATUS_MAP[s.status as CatStatus],
  lastVerifiedDate: s.lastVerifiedDate,
  eligibility: (s.eligibilityRules || []).map((r) => r.detail).filter(Boolean),
}));

const out = `// AUTO-GENERATED by scripts/agri-manifest.cts (npm run gen:agri-manifest) — do not edit by hand.
// Honest bootstrap manifest derived from the curated, source-cited catalog in
// src/lib/government-schemes-data.ts. lastVerifiedDate is preserved verbatim
// (2026-08-06) and NEVER bumped; the sync engine owns freshness from here on.
import type { CuratedScheme } from "./types.ts";

export const CURATED_SCHEMES: CuratedScheme[] = ${JSON.stringify(manifest, null, 2)};
`;

const target = path.resolve(__dirname, "../supabase/functions/agri-sync-worker/curated-schemes.ts");
fs.writeFileSync(target, out);
console.log(`Wrote ${manifest.length} schemes -> ${target}`);