// AUTO-GENERATED by scripts/agri-manifest.cts (npm run gen:agri-manifest) — do not edit by hand.
// Honest bootstrap manifest derived from the curated, source-cited catalog in
// src/lib/government-schemes-data.ts. lastVerifiedDate is preserved verbatim
// (2026-08-06) and NEVER bumped; the sync engine owns freshness from here on.
import type { CuratedScheme } from "./types.ts";

export const CURATED_SCHEMES: CuratedScheme[] = [
  {
    "id": "pm-kisan",
    "code": "PM-KISAN-2026",
    "name": "PM-KISAN Samman Nidhi Yojana",
    "nameHi": "प्रधानमंत्री किसान सम्मान निधि योजना",
    "category": "Income Support",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare (MoA&FW)",
    "benefits": "₹6,000 annual direct income support transferred in 3 equal installments of ₹2,000 directly to Aadhaar-seeded bank accounts.",
    "benefitAmount": "₹6,000 / Year",
    "benefitAmountNum": 6000,
    "description": "Central sector scheme providing ₹6,000 per year in 3 equal installments to all landholding farmer families across India.",
    "descriptionHi": "भारत के सभी भूमिधारक किसान परिवारों को प्रति वर्ष ₹6,000 की वित्तीय सहायता प्रदान करने वाली केंद्रीय योजना।",
    "applicationUrl": "https://pmkisan.gov.in/",
    "officialUrl": "https://pmkisan.gov.in/",
    "helpline": "155261 / 1800115526 (Toll-Free PM-KISAN Helpdesk)",
    "status": "rolling",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Must hold cultivable land in state land records (Khasra/Khatauni).",
      "Bank account must be linked with Aadhaar and e-KYC verified.",
      "Beneficiary or spouse must not have paid income tax in the last assessment year."
    ]
  },
  {
    "id": "pmfby",
    "code": "PMFBY-KHARIF-RABI",
    "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    "nameHi": "प्रधानमंत्री फसल बीमा योजना",
    "category": "Insurance",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "benefits": "Comprehensive crop insurance cover against yield loss due to non-preventable natural risks (drought, flood, pest attack). Premium rates: 1.5% for Rabi, 2% for Kharif, 5% for Commercial crops.",
    "benefitAmount": "Up to 100% Crop Value",
    "benefitAmountNum": 100000,
    "description": "Lowest premium crop insurance protecting farmers against pre-sowing to post-harvest yield losses.",
    "descriptionHi": "न्यूनतम प्रीमियम वाली फसल बीमा योजना जो बुवाई से लेकर कटाई के बाद के नुकसान से सुरक्षा देती है।",
    "applicationUrl": "https://pmfby.gov.in/",
    "officialUrl": "https://pmfby.gov.in/",
    "helpline": "14447 (Toll-Free Crop Insurance Helpline)",
    "status": "active",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Crop must be officially notified by State Govt for insurance coverage."
    ]
  },
  {
    "id": "kcc-crop-loan",
    "code": "KCC-CREDIT-2026",
    "name": "Kisan Credit Card (KCC) & Interest Subvention",
    "nameHi": "किसान क्रेडिट कार्ड (KCC) योजना",
    "category": "Credit & Loan",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare / RBI & NABARD",
    "benefits": "Concessional short-term crop loans up to ₹3 Lakh at an effective interest rate of only 4% per annum (after 3% prompt repayment incentive). No collateral required up to ₹1.6 Lakh.",
    "benefitAmount": "Up to ₹3,000,000 Credit Limit",
    "benefitAmountNum": 300000,
    "description": "Revolving credit facility providing hassle-free short term crop loans and working capital to farmers at 4% interest.",
    "descriptionHi": "किसानों को 4% ब्याज दर पर आसान अल्पकालिक फसल ऋण और कार्यशील पूंजी प्रदान करने वाली योजना।",
    "applicationUrl": "https://myscheme.gov.in/schemes/kcc",
    "officialUrl": "https://myscheme.gov.in/schemes/kcc",
    "helpline": "18001801551 (Kisan Call Centre Toll-Free)",
    "status": "rolling",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Borrowers above 60 years require a co-borrower.",
      "Active savings bank account with clean credit history."
    ]
  },
  {
    "id": "pmksy-drip",
    "code": "PMKSY-PDMC-2026",
    "name": "PMKSY Per Drop More Crop (Micro Irrigation Subsidy)",
    "nameHi": "प्रधानमंत्री कृषि सिंचाई योजना (सूक्ष्म सिंचाई सब्सिडी)",
    "category": "Irrigation",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare / Dept of Agriculture",
    "benefits": "55% subsidy for Small & Marginal Farmers (45% for Other Farmers) on installation of Drip and Sprinkler Irrigation systems.",
    "benefitAmount": "Up to 55% Subsidy",
    "benefitAmountNum": 55,
    "description": "Financial assistance for installing water-saving drip and sprinkler irrigation systems.",
    "descriptionHi": "पानी बचाने वाली ड्रिप और स्प्रिंकलर सिंचाई प्रणाली स्थापित करने के लिए वित्तीय सहायता।",
    "applicationUrl": "https://pmksy.gov.in/",
    "officialUrl": "https://pmksy.gov.in/",
    "helpline": "18001801551 (State Agriculture Micro-Irrigation Cell)",
    "status": "active",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Must have tube-well, canal connectivity, or farm pond.",
      "Requires registered land khatauni or long-term lease deed."
    ]
  },
  {
    "id": "smam-machinery",
    "code": "SMAM-FARM-EQUIP-2026",
    "name": "Sub-Mission on Agricultural Mechanization (SMAM / Agricultural Machinery Subsidy)",
    "nameHi": "कृषि यांत्रिकीकरण पर उप-मिशन (मशीनरी सब्सिडी)",
    "category": "Equipment",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "benefits": "40% to 80% financial subsidy on tractors, combine harvesters, laser land levelers, rotavators, power tillers, and Custom Hiring Centre (CHC) setup.",
    "benefitAmount": "40% to 80% Subsidy",
    "benefitAmountNum": 80,
    "description": "Subsidy scheme promoting farm mechanization and Custom Hiring Centres for modern farm equipment.",
    "descriptionHi": "आधुनिक कृषि उपकरणों पर सब्सिडी और कस्टम हायरिंग सेंटर को बढ़ावा देने वाली योजना।",
    "applicationUrl": "https://agrimachinery.nic.in/",
    "officialUrl": "https://agrimachinery.nic.in/",
    "helpline": "18001801551 (FARMS App Support)",
    "status": "active",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Women, SC, ST, and Small/Marginal farmers receive up to 50% for individual machines and 80% for CHC groups."
    ]
  },
  {
    "id": "pm-kusum-solar",
    "code": "PM-KUSUM-SOLAR-2026",
    "name": "PM-KUSUM Scheme (Solar Agriculture Pump Subsidy)",
    "nameHi": "प्रधानमंत्री कुसुम योजना (सौर ऊर्जा पंप सब्सिडी)",
    "category": "Subsidy",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of New and Renewable Energy (MNRE)",
    "benefits": "60% total subsidy (30% Central + 30% State Govt) for installing standalone Off-Grid Solar Agriculture Pumps up to 7.5 HP. Farmer pays only 40% (bank loan available for 30%).",
    "benefitAmount": "60% Solar Pump Subsidy",
    "benefitAmountNum": 60,
    "description": "Subsidy scheme for installing 3HP to 10HP solar powered irrigation pumps replacing diesel pumps.",
    "descriptionHi": "डीजल पंपों को बदलकर 3HP से 10HP सौर ऊर्जा संचालित सिंचाई पंप लगाने के लिए सब्सिडी योजना।",
    "applicationUrl": "https://pmkusum.mnre.gov.in/",
    "officialUrl": "https://pmkusum.mnre.gov.in/",
    "helpline": "18001803333 (MNRE Toll-Free Helpline)",
    "status": "active",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Must possess land suitable for installing solar panel array and pump."
    ]
  },
  {
    "id": "pkvy-organic",
    "code": "PKVY-ORGANIC-2026",
    "name": "Paramparagat Krishi Vikas Yojana (PKVY - Organic Farming)",
    "nameHi": "परंपरागत कृषि विकास योजना (जैविक खेती)",
    "category": "Organic Farming",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "benefits": "₹50,000 per hectare financial assistance over 3 years for organic inputs, PGS organic certification, processing, and green manure.",
    "benefitAmount": "₹50,000 / Hectare",
    "benefitAmountNum": 50000,
    "description": "Financial incentive and organic certification support to encourage chemical-free organic farming.",
    "descriptionHi": "रसायन मुक्त जैविक खेती को बढ़ावा देने के लिए वित्तीय प्रोत्साहन और जैविक प्रमाणन सहायता।",
    "applicationUrl": "https://pgsindia-ncof.gov.in/",
    "officialUrl": "https://pgsindia-ncof.gov.in/",
    "helpline": "18001801551 (National Centre of Organic Farming)",
    "status": "active",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Farmers must form a cluster of at least 20 farmers with combined 50 acres."
    ]
  },
  {
    "id": "shc-soil-health",
    "code": "SHC-NUTRIENT-2026",
    "name": "Soil Health Card Scheme (SHC & Free Soil Testing)",
    "nameHi": "मृदा स्वास्थ्य कार्ड योजना (मुफ्त मिट्टी जांच)",
    "category": "Soil & Inputs",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "benefits": "100% Free laboratory soil testing covering 12 parameter nutrient analyses (N, P, K, pH, EC, Organic Carbon, Micronutrients) & customized fertilizer dosage report every 2 years.",
    "benefitAmount": "100% Free Soil Test & Card",
    "benefitAmountNum": 100,
    "description": "Free soil testing card providing crop-wise nutrient recommendations to reduce fertilizer cost.",
    "descriptionHi": "उर्वरक लागत घटाने के लिए मुफ्त मिट्टी जांच कार्ड और फसलवार पोषक तत्व सिफारिश।",
    "applicationUrl": "https://soilhealth.dac.gov.in/",
    "officialUrl": "https://soilhealth.dac.gov.in/",
    "helpline": "18001801551 (Soil Health Card Helpdesk)",
    "status": "rolling",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Applicable for any cultivable farm parcel."
    ]
  },
  {
    "id": "rkvy-raftaar",
    "code": "RKVY-RAFTAAR-2026",
    "name": "Rashtriya Krishi Vikas Yojana (RKVY-RAFTAAR & Agri Startups)",
    "nameHi": "राष्ट्रीय कृषि विकास योजना (RKVY-रफ़्तार)",
    "category": "Subsidy",
    "level": "central",
    "applicableStates": [
      "All India"
    ],
    "ministry": "Ministry of Agriculture & Farmers Welfare",
    "benefits": "Grant-in-aid assistance up to ₹5 Lakh for Agripreneurs (Idea Stage) and up to ₹25 Lakh for Seed Stage Agri Startups & FPOs.",
    "benefitAmount": "Up to ₹2,500,000 Grant",
    "benefitAmountNum": 2500000,
    "description": "Innovation and agri-entrepreneurship grant scheme supporting value addition, processing, and smart tech.",
    "descriptionHi": "मूल्य संवर्धन, प्रसंस्करण और स्मार्ट एग्री-टेक को समर्थन देने वाली नवाचार अनुदान योजना।",
    "applicationUrl": "https://rkvy.nic.in/",
    "officialUrl": "https://rkvy.nic.in/",
    "helpline": "011-23382012 (RKVY Knowledge Partner Cell)",
    "status": "active",
    "lastVerifiedDate": "2026-08-06",
    "eligibility": [
      "Must present a viable project plan for agri-processing, technology, or FPO value addition."
    ]
  }
];
