// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    persistSession: true,
    autoRefreshToken: true,
    // The dedicated /auth/callback page owns the PKCE code exchange
    // (AuthCallback.tsx → exchangeCodeForSession). Leaving this at its default
    // `true` lets a concurrent getSession() consume the one-time code first and
    // the callback then fails with "code already used". Disabled so the exchange
    // happens exactly once, deterministically, on the callback route.
    detectSessionInUrl: false,
    storage: localStorage,
  }
});